### ISSUE TITLE
What a cool tool...fails to retrieve image count

### ISSUE THREAD

**Issue by richtong** [spinda/imagenetscraper#1]
What a great tool! I tried to run

```
imagenetscraper n00007846 person_images
```

And it doesn't seem to see the network or has format changed?

```
Retrieving synset target id
Retrieving image count
Failed to retrieve image count, is there a connection issue?
(no element found: line 1, column 0)
```

**Comment by spinda** [comment]
This is a problem on ImageNet's end, c.f. http://image-net.org/update-sep-17-2019:

> While conducting our study, since January 2019 we have disabled downloads of the full ImageNet data, except for the small subset of 1,000 categories used in the ImageNet Challenge. We are in the process of implementing our proposed remedies.

All we can do is wait for them to bring image downloads back online.
